{
 "title": "CI Jobs KPI",
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "Framework",
    "label": "Framework",
    "query": "dotnet, helm, docker, go, python, markdown "
   },
   {
    "name": "Stage",
    "label": "Stage",
    "query": "restore, test, lint, build, package, push"
   }
  ]
 },
 "panels": [
  {
   "title": "Total Usage",
   "type": "stat",
   "description": "Total CI job usage",
   "gridPos": { "h": 5, "w": 3, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(ci_${Framework}_${Stage}_total)"
    }
   ]
  },
  {
   "title": "Total Success",
   "type": "stat",
   "description": "Total passed CI job usage",
   "gridPos": { "h": 5, "w": 3, "x": 3, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(ci_${Framework}_${Stage}_total{status=\"success\"})"
    }
   ]
  },
  {
   "title": "Usage Per Project",
   "type": "timeseries",
   "description": "Usage Per Project",
   "gridPos": { "h": 10, "w": 10, "x": 6, "y": 0 },
   "targets": [
    { "expr": "ci_${Framework}_${Stage}_total", "legendFormat": "{{project}}-{{status}}" }
   ]
  },
  {
   "title": "Passed Duration Pie",
   "type": "piechart",
   "description": "Passed Duration Pie",
   "gridPos": { "h": 10, "w": 4, "x": 16, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "ci_${Framework}_${Stage}_duration_bucket{status=\"success\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Failed Duration Pie",
   "type": "piechart",
   "description": "Failed Duration Pie",
   "gridPos": { "h": 10, "w": 4, "x": 20, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "ci_${Framework}_${Stage}_duration_bucket{status=\"failed\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total Usage",
   "type": "stat",
   "description": "Total CI job usage",
   "gridPos": { "h": 5, "w": 3, "x": 0, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(sum by (project) (ci_${Framework}_${Stage}_total))"
    }
   ]
  },
  {
   "title": "Total Failed",
   "type": "stat",
   "description": "Total failed CI job usage",
   "gridPos": { "h": 5, "w": 3, "x": 3, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(ci_${Framework}_${Stage}_total{status=\"failed\"})"
    }
   ]
  }
 ]
}